DTel-HQ/dtel

Payment.md
=> Added Hifumi

Customer Support Reference.md
=> Added un-blacklisting section

In case of Emergency.md, Payment.md
Changelog:
- fixed grammatical errors
- fixed awkward sentences
=> Grammar check - ICoE and Payments

DiscordTel Guide.md, Useful Numbers.md, index.md
Just making sure noobs can understand the docs. ;)
=> Noob-friendly stuff

DiscordTel Guide.md
Changes:
- Made the guide more professional
- Fixed minor grammar errors
- Tweaked awkward sentences
- Made titles more tutorial-like
=> Changelog #5 - DiscordTel Guide

La guía en español de DiscordTel.md
New updated one accept this pull request not old one..
=> Create La guía en español de DiscordTel.md

index.js
Suggest stuff!
(also just change the var suggestionchannel to the id of the channel for it to work)
=> Add >suggest

menu.json
=> Revert "Update menu.json"

index.js
added "voice"mail, it will be triggered if the "to" end hangs up the call or if the call times out
(+ my own call shortcode for helping)
=> Add "voice"mail

Deutscher DiscordTel Guide.md, index.md
Created German translation of the Guide, mentioned matematrix as translator for this.
Please remove the DiscordTel Führer auf Deutsch.md file, and set the link for the languages.
=> Readthedocs

index.js
=> Fixed login

Deutscher DiscordTel Guide.md
Changed numeration, there were two 4s
=> Update Deutscher DiscordTel Guide.md

index.js
stops >suggest without a message in it. it's quite annoying.
(decided to do this because why not)
=> stop no characters in >suggest

commands/help.js
=> fixed your grammar once again

index.js
By adding this, the bot will check if the guild the command is run on is under a Discord outage. If it is, it will not allow the command to run, to avoid any exceptions being thrown because of the outage.
=> Add guild availability/outage checking

commands/help.js
.sendEmbed is a deprecated method, updated to .send
=> Removed deprecated methods

commands/ping.js
i removed the unnecessary Dtel title and made it look better tbh
=> made it look better

callcmds/hangup.js, callcmds/pickup.js, commands/backdoor.js, commands/call.js, commands/convert.js, commands/daily.js, commands/gblacklist.js, commands/help.js, commands/info.js, commands/ping.js, commands/refer.js, commands/suggest.js, commands/wizard.js, index.js, modules/fourOneOneHandler.js
- Replaced `${message.author.username}#${message.author.discriminator}` to `${message.author.tag}`
- Removed unnecessary commas
- Actually made the `fourOneOneHandler.js` find the files 😮
(retrieved from commit https://github.com/austinhuang0131/discordtel/commit/b651bee6aaf5acc70d984dc518c7bb4475222890)
=> housekeeping

index.js
I did it right this time and did it once every month with a notice and everything austin asked. I left a little thing that would put it in the bot-log channel but commented it out because it would get quite spammy.
nubbytm
=> Fix json files in index.js and auto-deassign number

events/guildCreate.js
when it joins a server, it's going to notify people that it should have Embed Links permission. and no it wont use an embed.
=> add a check to make sure bot has Embed Links permissions

index.js
A quick fix for the mailbox that exceeded the max char limit.
Also preventing users from exceeding the max char limit of embed fields.
=> Mailbox fix

README.md
=> Use Discord guild embeds for image links

callcmds/pickup.js
No, I didn't create this in my last PR
=> Remove the double }

commands/call.js
Hopefully stopping some people from hanging up after in less than 20 seconds...
=> Message when calling *611

commands/call.js
More better, should've done it like this last time
=> Including 0800 number

commands/rmstrike.js, commands/strike.js
-Don't let people unstrike themselves
-Let bosses strike cs
=> Some strike things

commands/balance.js
also I’d like to add `bal` as an alias but I dunno how to with this bot
=> grammar, oi

Configuration/config.js, Database/init.js, Internals/jobs.js
This update brings a monthly leaderboard of the number of votes.
The winner(s) will receive a prize in VIP Months.
=> Vote Rewarding Program

Commands/Public/contacts.js, Commands/Public/promote.js, Configuration/aliases.js, Internals/233.js, package-lock.json, package.json
I think it’s time for a version bump, but this pr mainly just adds logging for >promote and number renewal.
=> v3.2 I guess

Commands/Public/convert.js
=> mAjOr ChAnGe

Commands/Public/balance.js, Commands/Public/call.js, Commands/Public/daily.js, Commands/Public/lottery.js, Commands/Public/pay.js, Commands/Public/promote.js, Commands/Support/addcredit.js, Commands/Support/uinfo.js, Internals/233.js, Internals/jobs.js
This change (should) be purely code wise and have no visual effect.
=> update dts emoji references to use config.dtsEmoji

Events/message.js
title says all
not the most important change but it **might** help support members
=> prevent support members from being cancelled out while running unbusy due to being busy

Commands/Support/ninfo.js
Personally I don’t think a colour is enough (what if someone in CS is colourblind?), but this is realistically up to y’all.
=> ninfo: make it more clear if number VIP

Configuration/config.js, Events/ready.js, Internals/callHandler.js, Structures/DTelUser.js
because contributors are epic 👍
=> create contributor phone

Commands/Public/upgrade.js, Configuration/config.js
my codespace was pushing to the wrong repository >:(
=> move my commits

Commands/Public/pay.js, Commands/Public/upgrade.js, Configuration/config.js
currently I've set it to a 15% fee (vs 27% for normal users). if this is okay I'll make the required changes to our advertising, if not let me know and I'll tweak it. until the rate is certain I'll keep this marked as a draft.
=> feat: reduced >pay fee for vip users

Internals/callHandler.js
its just a copy&paste not rly that hard
=> fix lost access 611 bug

Commands/Support/blacklist.js, Internals/callHandler.js
this also improves the bl message
=> fix: prevent blacklisted users from messaging in calls

.github/CONTRIBUTING.md, README.md
- Changed the `contributing.md` in .github.
- Changed the readme file to include more information and styled it differently.
Resolves #282
=> Resolve: 282 add and change documentation

.eslintrc.js, src/commands/call/backdoor.js, src/commands/call/cinfo.js, src/commands/call/ninfo.js, src/commands/call/permcheck.js, src/commands/private/assign.js, src/commands/private/stats.js, src/commands/public/call.js, src/commands/public/contacts.js, src/commands/public/convert.js, src/commands/public/mailbox.js, src/commands/public/message.js, src/commands/public/upgrade.js, src/commands/support/backdoor.js, src/commands/support/minfo.js, src/configuration/embeds.js, src/dtel.js, src/embed.js
This brings several embeds into `embeds.js`.
*Resolves #287*
=> refactor: unify similar embeds

README.md
this matters because of OCD & because discord updated their branding
=> update color of badges for new discord branding
